### ISSUE TITLE
关于zhenxun安装的bug以及1个疑问

### ISSUE THREAD

**Issue by whx9986** [TimeRainStarSky/TRSS_Script#2]
bug:使用的是阿里云服务器，在安装zhenxun时，会遇到如下报错
![image](https://github.com/TimeRainStarSky/TRSS_Script/assets/58754399/4d08edfd-42b7-43f1-b37b-1535738bd1e0)
![image](https://github.com/TimeRainStarSky/TRSS_Script/assets/58754399/d538e046-737f-455c-aa24-52568f8ea6a4)
重试也是无效的，使用的GitHub源
-----------------------------------------------------------------------
疑问：在附加功能那里，配置好clash并启动后，在fish执行命令
`export http_proxy=http://127.0.0.1:7890`
`export https_proxy=http://127.0.0.1:7890`
`export no_proxy="localhost, 127.0.0.1"`
然后`curl www.google.com`是能访问外网的，但是yunzai的[繁星插件](https://github.com/AFanSKyQs/FanSky_Qs)中的OpenAI功能无法使用
![image](https://github.com/TimeRainStarSky/TRSS_Script/assets/58754399/62982a8b-6739-4bca-9871-19a9d8d5479c)
![image](https://github.com/TimeRainStarSky/TRSS_Script/assets/58754399/900f15b2-3d92-4314-b0c7-2e1ac1936e48)
但在电脑上部署yunzai和繁星时，开启clash测试是可以的，docker不太了解，不知道为什么不行，是还需要进行什么操作才能配置好代理吗？
之前那个没日志，现在是报这个错了：
![image](https://github.com/TimeRainStarSky/TRSS_Script/assets/58754399/db6f0a53-a3a0-4805-8168-6943cc982f85)

**Comment by TimeRainStarSky** [comment]
1. 真寻不支持py3.11，找作者适配
2. 打开Socks5

**Comment by whx9986** [comment]
当我打开socks5之后，再去启动yunzai就会这样，原版和喵版都是，而且关不掉，只能重启容器
![image](https://github.com/TimeRainStarSky/TRSS_Script/assets/58754399/7eccb0b3-fc6b-43e5-bbac-06f1e08366ed)
clash和socks5配置如下：
![image](https://github.com/TimeRainStarSky/TRSS_Script/assets/58754399/09ba5829-179b-4252-ad38-2e176c5d3453)
![image](https://github.com/TimeRainStarSky/TRSS_Script/assets/58754399/7ff0810c-0735-418b-99f8-cbeaca7d87c1)
请问这该怎么办？
正常启动的时候是下图这样
![image](https://github.com/TimeRainStarSky/TRSS_Script/assets/58754399/4b6fa3f7-bbbe-456c-a684-81247bf3e99b)

**Comment by TimeRainStarSky** [comment]
> 当我打开socks5之后，再去启动yunzai就会这样，原版和喵版都是，而且关不掉，只能重启容器
> ![image](https://github.com/TimeRainStarSky/TRSS_Script/assets/58754399/7eccb0b3-fc6b-43e5-bbac-06f1e08366ed)
> clash和socks5配置如下：
> ![image](https://github.com/TimeRainStarSky/TRSS_Script/assets/58754399/09ba5829-179b-4252-ad38-2e176c5d3453)
> ![image](https://github.com/TimeRainStarSky/TRSS_Script/assets/58754399/7ff0810c-0735-418b-99f8-cbeaca7d87c1)
> 请问这该怎么办？
> 正常启动的时候是下图这样
> ![image](https://github.com/TimeRainStarSky/TRSS_Script/assets/58754399/4b6fa3f7-bbbe-456c-a684-81247bf3e99b)
> 
> 

先开Clash
