### ISSUE TITLE
关于在终端绘制图形界面

### ISSUE THREAD

**Issue by xmexg** [TimeRainStarSky/TRSS_Script#4]
请问这种在终端显示出可通过按键操作的图形界面是如何实现的？好奇![6cdd63ab4a91f87c.jpg](https://github.com/TimeRainStarSky/TRSS_Script/assets/42137636/50a359d0-2fe4-4feb-963c-2f2a6dbd7822)

**Comment by TimeRainStarSky** [comment]
dialog
