### ISSUE TITLE
脚本占用大量资源

### ISSUE THREAD

**Issue by NotIvny** [TimeRainStarSky/TRSS_Script#5]
![IMG_20230723_171301](https://github.com/TimeRainStarSky/TRSS_Script/assets/125482125/e2b09d2c-ed01-445e-a811-6764967954a8)
平均负载直接干到6，只运行了LittlePaimon
_(issue发错仓库了 --> https://github.com/TimeRainStarSky/TRSS_AllBot)_

**Comment by TimeRainStarSky** [comment]
把完整进程树发出来，看是什么进程导致的

**Comment by NotIvny** [comment]
> 把完整进程树发出来，看是什么进程导致的

![Screenshot_2023-07-24-18-39-58-82_61c78dc80ee02b53007c815fefe993e3](https://github.com/TimeRainStarSky/TRSS_Script/assets/125482125/694def51-ace6-4f9a-9f61-3c2c6798f615)

**Comment by NotIvny** [comment]
> 把完整进程树发出来，看是什么进程导致的

找到问题了，在有bot进程后我想进选择bot的gui，没找着命令，然后发现tsab 1234这样可以进，然后每隔几秒就会重复执行main.sh 1234，输命令次数多了就占用了大量资源

**Comment by NotIvny** [comment]
> > 把完整进程树发出来，看是什么进程导致的
> 
> ![Screenshot_2023-07-24-18-39-58-82_61c78dc80ee02b53007c815fefe993e3](https://user-images.githubusercontent.com/125482125/255566089-694def51-ace6-4f9a-9f61-3c2c6798f615.jpg)
![Screenshot_2023-07-24-22-34-06-78_61c78dc80ee02b53007c815fefe993e3](https://github.com/TimeRainStarSky/TRSS_Script/assets/125482125/61ee3e34-a297-45a3-93a1-71e69686c754)

找到问题了，用不合法的命令导致的，如tsab 1234会导致程序反复执行bash main.sh.x 1234，当时不知道怎么在有bot进程的情况下进入选择bot的界面就这样弄的...
