### ISSUE TITLE
mt管理器脚本安装失败

### ISSUE THREAD

**Issue by uchzmal** [TimeRainStarSky/TRSS_Script#7]
如图
![Screenshot_2023-09-24-22-33-34-103_bin mt plus](https://github.com/TimeRainStarSky/TRSS_Script/assets/117048798/121b6af3-84bb-43fa-8766-e9e519944240)
![Screenshot_2023-09-24-22-33-06-386_bin mt plus](https://github.com/TimeRainStarSky/TRSS_Script/assets/117048798/c6983b35-df9d-4140-9c78-a3a179355141)
![Screenshot_2023-09-24-22-32-58-732_bin mt plus](https://github.com/TimeRainStarSky/TRSS_Script/assets/117048798/6e3393cb-ea38-4159-ba27-17ca70792330)

**Comment by TimeRainStarSky** [comment]
降级到1.13.8以下
https://dl.mt2.cn/MT2.13.8.apk
