### ISSUE TITLE
trss.me网站上的ghproxy.com加速源该换了

### ISSUE THREAD

**Issue by SunshineboyZj** [TimeRainStarSky/TRSS_Script#8]
主域名（ghproxy.com）被墙了，换成二级域名mirror.ghproxy.com即可
![Screenshot_20231206_041807](https://github.com/TimeRainStarSky/TRSS_Script/assets/81549837/b9bb52d3-0759-4b38-8812-8dba1d5e467d)

**Comment by TimeRainStarSky** [comment]
已更新
